import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, HeadContent, Scripts } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";
import { Github, ArrowUpRight, Menu, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ChatWidget } from "@/components/chat-widget";
import appCss from "../styles.css?url";

export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({
 head: () => ({ meta: [{ charSet:"utf-8" }, { name:"viewport", content:"width=device-width, initial-scale=1" }], links: [{ rel:"stylesheet",href:appCss }, { rel:"preconnect",href:"https://fonts.googleapis.com" }, { rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous" }, { rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap" }, { rel:"icon",href:"/favicon.svg",type:"image/svg+xml" }] }),
 shellComponent: ({children}:{children:ReactNode}) => <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>,
 component: Root,
 notFoundComponent: () => <main className="site-shell min-h-[70vh] flex flex-col justify-center"><h1 className="font-display text-6xl">Lost in space.</h1><p className="text-muted-foreground mt-4">That page isn’t here.</p><Button asChild className="w-fit mt-8"><Link to="/">Head home</Link></Button></main>,
});
function Root(){ const {queryClient}=Route.useRouteContext(); const [menu,setMenu]=useState(false); return <QueryClientProvider client={queryClient}>
<header className="sticky top-0 z-40 border-b border-border bg-background/90 backdrop-blur-xl"><div className="site-shell h-[72px] flex items-center justify-between gap-6"><Link to="/" className="font-display font-bold text-xl tracking-normal flex items-center gap-2"><span className="text-primary text-2xl">✳</span> clayton<span className="text-primary">.</span></Link><nav className="hidden md:flex items-center gap-9 text-sm text-muted-foreground"><Link to="/" activeProps={{className:"text-foreground"}} className="hover:text-foreground">Home</Link><Link to="/lab" activeProps={{className:"text-foreground"}} className="hover:text-foreground">The Lab</Link><Link to="/contact" activeProps={{className:"text-foreground"}} className="hover:text-foreground">Contact</Link></nav><div className="hidden md:flex items-center gap-5"><a href="https://github.com/" target="_blank" rel="noopener noreferrer" aria-label="GitHub" className="text-muted-foreground hover:text-primary"><Github size={19}/></a><Button asChild size="sm" variant="outline" className="rounded-sm"><Link to="/contact">Say hello <ArrowUpRight size={14}/></Link></Button></div><Button variant="ghost" size="icon" className="md:hidden" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div>{menu&&<nav className="md:hidden site-shell pb-5 flex flex-col gap-4 text-sm"><Link to="/" onClick={()=>setMenu(false)}>Home</Link><Link to="/lab" onClick={()=>setMenu(false)}>The Lab</Link><Link to="/contact" onClick={()=>setMenu(false)}>Contact</Link></nav>}</header>
<Outlet/>
<footer className="border-t border-border py-12 mt-24"><div className="site-shell flex flex-col md:flex-row justify-between gap-6 text-sm text-muted-foreground"><div><span className="font-display text-foreground font-semibold">clayton<span className="text-primary">.</span></span><p className="mt-2">Building useful things, one idea at a time.</p></div><div className="flex items-center gap-6"><Link to="/lab" className="hover:text-primary">The Lab</Link><a href="https://github.com/" target="_blank" rel="noopener noreferrer" className="hover:text-primary">GitHub</a><Link to="/contact" className="hover:text-primary">Contact</Link><Link to="/admin" className="hover:text-primary">Admin</Link></div></div></footer><ChatWidget/>
</QueryClientProvider> }
