import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { getLabItems } from "@/lib/portfolio";
import { LabCard, SectionLabel } from "@/components/portfolio-ui";
export const Route=createFileRoute("/lab")({head:()=>({meta:[{title:"The Lab — Clayton Aylor"},{name:"description",content:"Small experiments, useful tools, and open-source ideas from Clayton Aylor's project lab."},{property:"og:title",content:"The Lab — Clayton Aylor"},{property:"og:description",content:"A space for side experiments, micro-tools, and creative code."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:LabPage});
const filters=["All","Experiments","Tools","Open Source"];
function LabPage(){const [filter,setFilter]=useState("All");const {data:items=[]}=useQuery({queryKey:["lab"],queryFn:getLabItems});const shown=items.filter(x=>filter==="All"||x.category===filter);return <main className="min-h-[65vh]"><section className="border-b border-border starfield"><div className="site-shell pt-20 pb-20 md:pt-28 md:pb-24"><SectionLabel>Explorations / Side quests</SectionLabel><h1 className="font-display text-5xl md:text-7xl font-medium mt-6">Welcome to <span className="text-primary">the lab.</span></h1><p className="text-lg text-muted-foreground max-w-xl leading-relaxed mt-6">A collection of small experiments, useful tools, and ideas that were too fun not to try.</p></div></section><section className="site-shell pt-12"><div className="flex flex-wrap gap-2 mb-9" role="group" aria-label="Filter lab items">{filters.map(f=><Button key={f} variant={filter===f?"default":"outline"} className="rounded-sm" onClick={()=>setFilter(f)}>{f}</Button>)}</div>{shown.length?<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{shown.map((item,i)=><LabCard key={item.id} item={item} index={i}/>)}</div>:<p className="text-muted-foreground py-20">Nothing in this corner of the lab yet.</p>}</section></main>}
