import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { ArrowLeft, ArrowUpRight, Github, ExternalLink, Monitor, Server, Database, Cloud, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getProjects } from "@/lib/portfolio";
import { SectionLabel } from "@/components/portfolio-ui";
import preview from "@/assets/project-preview.jpg";
export const Route = createFileRoute("/projects/$slug")({head:({params})=>({meta:[{title:`${params.slug.replaceAll('-', ' ')} — Clayton Aylor`},{name:"description",content:"Explore the story, architecture, and challenges behind a Clayton Aylor project."},{property:"og:title",content:`Project story — Clayton Aylor`},{property:"og:description",content:"A closer look at the idea, system, and work behind a project."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}),component:ProjectPage});
const nodes=[{name:"Client",sub:"The experience",icon:Monitor,detail:"The browser-facing interface: responsive views, interactions, and the details that make the product feel good."},{name:"API routes",sub:"The logic",icon:Server,detail:"Server-side routes validate requests, coordinate data, and keep sensitive operations away from the browser."},{name:"Database",sub:"The memory",icon:Database,detail:"Structured records keep the application’s information consistent and available across sessions."},{name:"Services",sub:"The connections",icon:Cloud,detail:"External integrations extend the app with data and capabilities beyond its own walls."}] as const;
function ProjectPage(){const {slug}=Route.useParams();const {data:projects=[],isLoading}=useQuery({queryKey:["projects"],queryFn:getProjects});const p=projects.find(x=>x.slug===slug);const [active,setActive]=useState(0);if(isLoading)return <main className="site-shell py-24 text-muted-foreground">Loading project…</main>;if(!p)return <main className="site-shell py-24"><h1 className="font-display text-4xl">Project not found.</h1><Button asChild className="mt-6"><Link to="/">Back home</Link></Button></main>;return <main><div className="site-shell pt-12 md:pt-20"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft size={15}/> Back to home</Link><div className="mt-16"><SectionLabel>Project deep dive / {p.category}</SectionLabel><div className="flex flex-col md:flex-row justify-between md:items-end gap-8 mt-7"><div><h1 className="font-display text-5xl md:text-7xl font-medium">{p.title}<span className="text-primary">.</span></h1><p className="text-muted-foreground text-lg md:text-xl max-w-2xl mt-6 leading-relaxed">{p.summary}</p></div><div className="flex gap-3 shrink-0">{p.demo_url&&<Button asChild className="rounded-sm"><a href={p.demo_url} target="_blank" rel="noopener noreferrer">Live demo <ExternalLink size={15}/></a></Button>}{p.github_url&&<Button asChild variant="outline" className="rounded-sm"><a href={p.github_url} target="_blank" rel="noopener noreferrer">GitHub <Github size={15}/></a></Button>}</div></div></div><div className="mt-12 md:mt-16 border border-border overflow-hidden rounded-sm aspect-[1.6] md:aspect-[2.15] bg-card"><img src={p.image_url||preview} alt={`${p.title} project preview`} width={1200} height={768} className="w-full h-full object-cover"/></div></div>
<section className="site-shell mt-24 grid md:grid-cols-[1fr_2fr] gap-8 md:gap-20"><SectionLabel>01 / The story & spark</SectionLabel><div><h2 className="font-display text-3xl md:text-4xl">Why this exists.</h2><p className="mt-6 text-muted-foreground leading-[1.9]">{p.story}</p><p className="mt-5 text-foreground/80 leading-[1.9]">{p.idea}</p></div></section>
<section className="mt-24 py-20 border-y border-border bg-card/30"><div className="site-shell"><SectionLabel>02 / System architecture</SectionLabel><div className="flex flex-col md:flex-row justify-between gap-6 mt-6 mb-12"><h2 className="font-display text-3xl md:text-4xl">How it fits together.</h2><p className="text-muted-foreground text-sm max-w-sm">Select a part of the system to take a closer look.</p></div><div className="grid lg:grid-cols-[1.7fr_1fr] gap-6"><div className="border border-border bg-background rounded-sm p-5 md:p-10 flex flex-wrap items-center justify-center gap-3 md:gap-5 min-h-56">{nodes.map((n,i)=>{const Icon=n.icon;return <div key={n.name} className="flex items-center gap-3 md:gap-5"><Button variant="outline" onClick={()=>setActive(i)} className={`h-auto min-w-27 md:min-w-32 flex-col gap-2 py-5 rounded-sm ${active===i?'border-primary bg-accent text-primary':''}`}><Icon size={22} strokeWidth={1.5}/><span className="text-xs">{n.name}</span></Button>{i<3&&<ChevronRight size={16} className="text-muted-foreground hidden sm:block"/>}</div>})}</div><div className="border border-border bg-card rounded-sm p-7 flex flex-col justify-center"><span className="text-xs font-mono uppercase tracking-widest text-primary">0{active+1} / 04</span><h3 className="font-display text-2xl mt-4">{(nodes[active] ?? nodes[0]).name}</h3><p className="text-sm text-primary mt-1">{(nodes[active] ?? nodes[0]).sub}</p><p className="text-muted-foreground text-sm leading-relaxed mt-5">{(nodes[active] ?? nodes[0]).detail}</p></div></div><p className="text-sm text-muted-foreground mt-6 leading-relaxed max-w-3xl">{p.architecture}</p></div></section>
<section className="site-shell py-24 grid md:grid-cols-[1fr_2fr] gap-8 md:gap-20"><SectionLabel>03 / The details</SectionLabel><div><h2 className="font-display text-3xl md:text-4xl">The interesting bits.</h2><h3 className="text-primary text-xs uppercase tracking-widest mt-10 mb-4">Challenges solved</h3><p className="text-muted-foreground leading-[1.9]">{p.challenges}</p><h3 className="text-primary text-xs uppercase tracking-widest mt-10 mb-4">Built with</h3><div className="flex flex-wrap gap-2">{p.stack.map(s=><span key={s} className="border border-border rounded-sm px-3 py-2 text-sm text-muted-foreground">{s}</span>)}</div><Button asChild variant="outline" className="mt-12 rounded-sm"><Link to="/">More projects <ArrowUpRight size={15}/></Link></Button></div></section></main>}
