import { useEffect, useRef, useState } from "react";
import { useNavigate, useRouterState } from "@tanstack/react-router";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, type UIMessage } from "ai";
import { MessageCircle, X, Plus, ArrowLeft, Trash2, Orbit } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Conversation, ConversationContent, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputTextarea, PromptInputFooter, PromptInputSubmit } from "@/components/ai-elements/prompt-input";
import { Shimmer } from "@/components/ai-elements/shimmer";
const KEY="clayton-chat-threads";
type Thread={id:string;title:string;updatedAt:number;messages:UIMessage[]};
function loadThreads():Thread[]{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return []}}
function saveThreads(t:Thread[]){localStorage.setItem(KEY,JSON.stringify(t))}
function ChatContent({thread,onSave}:{thread:Thread;onSave:(messages:UIMessage[])=>void}){
 const textarea=useRef<HTMLTextAreaElement>(null);const {messages,sendMessage,status,stop,error}=useChat({id:thread.id,messages:thread.messages,transport:new DefaultChatTransport({api:"/api/chat",body:{conversationId:thread.id}}),onError:(e)=>console.error("Chat error",e)});
 useEffect(()=>{onSave(messages)},[messages,onSave]);useEffect(()=>{textarea.current?.focus()},[thread.id,status]);
 const submit=(text:string)=>{if(!text.trim()||status==="submitted"||status==="streaming")return;sendMessage({text:text.trim()});requestAnimationFrame(()=>textarea.current?.focus())};
 return <><div className="flex-1 min-h-0"><Conversation className="h-full"><ConversationContent className="p-5 gap-5">{messages.length===0&&<div className="pt-9 pb-6"><div className="w-11 h-11 rounded-full border border-primary/40 text-primary grid place-items-center mb-5"><Orbit size={23}/></div><h3 className="font-display text-2xl">Hey there, curious human.</h3><p className="text-sm leading-relaxed text-muted-foreground mt-3">Ask me about Clayton’s work, what’s in the lab, or the ideas behind this place.</p><div className="flex flex-wrap gap-2 mt-6">{["What does Clayton build?","What’s in the lab?","Tell me about the projects"].map(s=><Button key={s} variant="outline" size="sm" className="rounded-sm text-xs h-auto py-2 whitespace-normal" onClick={()=>submit(s)}>{s}</Button>)}</div></div>}{messages.map(m=><Message key={m.id} from={m.role}><MessageContent className={m.role==="user"?"!bg-primary !text-primary-foreground !rounded-sm":"!bg-transparent"}>{m.parts.map((part,i)=>part.type==="text"?<MessageResponse key={i}>{part.text}</MessageResponse>:null)}</MessageContent></Message>)}{status==="submitted"&&<div className="text-sm text-primary"><Shimmer>Thinking...</Shimmer></div>}{error&&<p role="alert" className="text-sm text-destructive">{error.message||"Chat couldn’t respond. Please try again."}</p>}</ConversationContent><ConversationScrollButton/></Conversation></div><div className="p-3 border-t border-border"><PromptInput onSubmit={({text})=>submit(text)}><PromptInputTextarea ref={textarea} placeholder="Ask me anything…" className="min-h-16"/><PromptInputFooter className="justify-end"><PromptInputSubmit status={status} onStop={stop} className="size-8 rounded-sm"/></PromptInputFooter></PromptInput><p className="text-[10px] text-muted-foreground text-center mt-2">Answers may be imperfect. Ask Clayton for the real story.</p></div></>
}
export function ChatWidget(){const navigate=useNavigate();const pathname=useRouterState({select:s=>s.location.pathname});const threadId=pathname.startsWith("/chat/")?decodeURIComponent(pathname.slice(6)):null;const [open,setOpen]=useState(false);const [threads,setThreads]=useState<Thread[]>([]);const [ready,setReady]=useState(false);const [list,setList]=useState(false);
 useEffect(()=>{let items=loadThreads();if(!items.length){items=[{id:crypto.randomUUID(),title:"New conversation",updatedAt:Date.now(),messages:[]}];saveThreads(items)}setThreads(items);setReady(true)},[]);
 useEffect(()=>{if(threadId)setOpen(true)},[threadId]);
  useEffect(()=>{if(open&&ready&&!threadId){const first=threads[0];if(first)navigate({to:"/chat/$threadId",params:{threadId:first.id}})}},[open,ready,threadId,threads,navigate]);
 const active=threads.find(t=>t.id===threadId);const create=()=>{const t={id:crypto.randomUUID(),title:"New conversation",updatedAt:Date.now(),messages:[]};setThreads(prev=>{const next=[t,...prev];saveThreads(next);return next});setList(false);setOpen(true);navigate({to:"/chat/$threadId",params:{threadId:t.id}})};
 const select=(id:string)=>{setList(false);navigate({to:"/chat/$threadId",params:{threadId:id}})};
 const remove=(id:string)=>{setThreads(prev=>{const next=prev.filter(t=>t.id!==id);saveThreads(next);return next});if(threadId===id){const other=threads.find(t=>t.id!==id);if(other)select(other.id);else create()}};
 const save=(messages:UIMessage[])=>setThreads(prev=>{const old=prev.find(t=>t.id===threadId);if(!old||JSON.stringify(old.messages)===JSON.stringify(messages))return prev;const title=messages.find(m=>m.role==="user")?.parts.find(p=>p.type==="text")?.text?.slice(0,34)||old.title;const next=prev.map(t=>t.id===threadId?{...t,messages,title,updatedAt:Date.now()}:t);saveThreads(next);return next});
 const show=()=>{setOpen(true);if(!threadId){const first=threads[0];if(first)select(first.id)}};
 return <>{!open&&<Button aria-label="Open Clayton's companion" title="Ask about Clayton" onClick={show} className="fixed bottom-5 right-5 z-50 size-14 rounded-full shadow-[0_0_35px_var(--glow)] border border-primary/30"><Orbit size={23}/></Button>}{open&&<div className="fixed z-50 bottom-3 right-3 left-3 sm:left-auto sm:bottom-5 sm:right-5 sm:w-[390px] h-[min(620px,calc(100dvh-30px))] border border-border rounded-md bg-card shadow-[0_18px_70px_var(--glow)] flex flex-col overflow-hidden"><div className="flex items-center gap-3 px-4 py-3 border-b border-border shrink-0"><Button variant="ghost" size="icon" className="size-8" aria-label="Conversations" title="Conversations" onClick={()=>setList(!list)}>{list?<ArrowLeft size={17}/>:<MessageCircle size={17}/>}</Button><div className="flex-1 min-w-0"><div className="font-display font-semibold truncate">{list?"Conversations":"Clayton’s companion"}</div><div className="text-[10px] text-primary">A little guide to this corner of the internet</div></div><Button variant="ghost" size="icon" className="size-8" aria-label="New conversation" title="New conversation" onClick={create}><Plus size={18}/></Button><Button variant="ghost" size="icon" className="size-8" aria-label="Close chat" title="Close chat" onClick={()=>setOpen(false)}><X size={18}/></Button></div>{list?<div className="p-3 overflow-y-auto flex-1">{threads.sort((a,b)=>b.updatedAt-a.updatedAt).map(t=><div key={t.id} className="flex items-center border-b border-border"><Button variant="ghost" onClick={()=>select(t.id)} className="flex-1 justify-start truncate font-normal">{t.title}</Button><Button variant="ghost" size="icon" title="Delete conversation" aria-label={`Delete ${t.title}`} onClick={()=>remove(t.id)}><Trash2 size={15}/></Button></div>)}</div>:ready&&active?<ChatContent key={active.id} thread={active} onSave={save}/>:<div className="p-8 text-muted-foreground text-sm">Choose a conversation to start chatting.</div>}</div>}</>}
